# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.CharField(max_length=200)),
                ('suit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=10)),
                ('bet', models.IntegerField(default=0)),
                ('player_total_points', models.IntegerField(default=0)),
                ('dealer_total_points', models.IntegerField(default=0)),
                ('player_winning_status', models.CharField(max_length=10)),
                ('dealer_winning_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackjack.GameModel'),
        ),
    ]
