# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='numeric_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='dealer_winning_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='player_winning_status',
            field=models.BooleanField(default=False),
        ),
    ]
